CHUGIN_NAME=OnsetDetector

CXX_MODULES=OnsetDetector.cpp

mi=../../eurorack

CC_MODULES=$(mi)/stmlib/utils/random.cc \
	$(mi)/stmlib/dsp/units.cc

FLAGS+=-I$(mi) \
	-I$(mi)/stmlib

include ../common/makefile
